/**
 * Definition for this library.
 * 
 * Allow imports without crossing
 * 
 */

/** Reason codes for MQTT connections.          */
const IOREASON = {
    "SUCCESS": /*                               */0,
    "GRANTED_QOS_0": /*                         */1,
    "GRANTED_QOS_1": /*                         */2,
    "GRANTED_QOS_2": /*                         */3,
    "DISCONNECT_WITH_WILL_MESSAGE": /*          */4,
    "NO_MATCHING_SUBSCRIBERS": /*               */16,
    "NO_SUBSCRIPTION_EXISTED": /*               */17,
    "CONTINUE_AUTHENTICATION": /*               */24,
    "RE-AUTHENTICATE": /*                       */25,
    "UNSPECIFIED_ERROR": /*                     */128,
    "MALFORMED_PACKET": /*                      */129,
    "PROTOCOL_ERROR": /*                        */130,
    "IMPLEMENTATION_SPECIFIC_ERROR": /*         */131,
    "UNSUPPORTED_PROTOCOL_VERSION": /*          */132,
    "CLIENT_IDENTIFIER_NOT_VALID": /*           */133,
    "BAD_USER_NAME_OR_PASSWORD": /*             */134,
    "NOT_AUTHORIZED": /*                        */135,
    "SERVER_UNAVAILABLE": /*                    */136,
    "SERVER_BUSY": /*                           */137,
    "BANNED": /*                                */138,
    "SERVER_SHUTTING_DOWN": /*                  */139,
    "BAD_AUTHENTICATION_METHOD": /*             */140,
    "KEEP_ALIVE_TIMEOUT": /*                    */141,
    "TIMEOUT": /*                               */141,
    "SESSION_TAKEN_OVER": /*                    */142,
    "TOPIC_FILTER_INVALID": /*                  */143,
    "TOPIC_NAME_INVALID": /*                    */144,
    "PACKET_IDENTIFIER_IN_USE": /*              */145,
    "PACKET_IDENTIFIER_NOT_FOUND": /*           */146,
    "RECEIVE_MAXIMUM_EXCEEDED": /*              */147,
    "TOPIC_ALIAS_INVALID": /*                   */148,
    "PACKET_TOO_LARGE": /*                      */149,
    "MESSAGE_RATE_TOO_HIGH": /*                 */150,
    "QUOTA_EXCEEDED": /*                        */151,
    "ADMINISTRATIVE_ACTION": /*                 */152,
    "PAYLOAD_FORMAT_INVALID": /*                */153,
    "RETAIN_NOT_SUPPORTED": /*                  */154,
    "QOS_NOT_SUPPORTED": /*                     */155,
    "USE_ANOTHER_SERVER": /*                    */156,
    "SERVER_MOVED": /*                          */157,
    "SHARED_SUBSCRIPTIONS_NOT_SUPPORTED": /*    */158,
    "CONNECTION_RATE_EXCEEDED": /*              */159,
    "MAXIMUM_CONNECT_TIME": /*                  */160,
    "SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED": /**/161,
    "WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED": /*  */162,
    "TLS_ERROR": /*                             */249,
    "SOCKET_CLOSED": /*                         */250,
    "SOCKET_ERROR": /*                          */251,
    "CLOSED_BY_REQUEST": /*                     */252,
    "ID_ALREADY_IN_USE": /*                     */253,
    "REASON_CODES": {
        0: "Success",
        1: "Granted QoS 0",
        2: "Granted QoS 1",
        3: "Granted QoS 2",
        4: "Disconnect with Will Message",
        16: "No Matching Subscribers",
        17: "No Subscription Existed",
        24: "Continue Authentication",
        25: "Re-authenticate",
        128: "Unspecified Error",
        129: "Malformed Packet",
        130: "Protocol Error",
        131: "Implementation Specific Error",
        132: "Unsupported Protocol Version",
        133: "Client Identifier Not Valid",
        134: "Bad User Name or Password",
        135: "Not Authorized",
        136: "Server Unavailable",
        137: "Server Busy",
        138: "Banned",
        139: "Server Shutting Down",
        140: "Bad Authentication Method",
        141: "Keep Alive Timeout",
        142: "Session Taken Over",
        143: "Topic Filter Invalid",
        144: "Topic Name Invalid",
        145: "Packet Identifier in Use",
        146: "Packet Identifier Not Found",
        147: "Receive Maximum Exceeded",
        148: "Topic Alias Invalid",
        149: "Packet Too Large",
        150: "Message Rate Too High",
        151: "Quota Exceeded",
        152: "Administrative Action",
        153: "Payload Format Invalid",
        154: "Retain Not Supported",
        155: "QoS Not Supported",
        156: "Use Another Server",
        157: "Server Moved",
        158: "Shared Subscriptions Not Supported",
        159: "Connection Rate Exceeded",
        160: "Maximum Connect Time",
        161: "Subscription Identifiers Not Supported",
        162: "Wildcard Subscriptions Not Supported",
        250: "TLS Error",
        250: "Socket Closed",
        251: "Socket Error",
        252: "Closed by Request",
        253: "ID Already In Use",
    },
    /** Gets the reason code description
     * @param {Number} code 
     * @returns {String} */
    getReason(code) {
        return IOREASON.REASON_CODES[code] || "Unknown Reason";
    }
};
/** Available packet enumaration    */
const PACK_TYPE = {
    CONNECT:        /**/ 0x10,
    CON_ACK:        /**/ 0x20,
    CONNACK:        /**/ 0x20,
    PUBLISH:        /**/ 0x30,
    PUB_ACK:        /**/ 0x40,
    PUB_RECEIVE:    /**/ 0x50,
    PUB_RELEASE:    /**/ 0x60,
    PUB_COMPLETE:   /**/ 0x70,
    SUBSCRIBE:      /**/ 0x80,
    SUBACK:         /**/ 0x90,
    UNSUBSCRIBE:    /**/ 0xa0,
    UNSUBACK:       /**/ 0xb0,
    PING_REQUEST:   /**/ 0xc0,
    PING_RESPONSE:  /**/ 0xd0,
    DISCONNECT:     /**/ 0xe0,
    AUTH:           /**/ 0xf0,
    CLIENT_HELLO:   /**/ 0xf1,
    SERVER_HELLO:   /**/ 0xf2,
    EXCHANGE_DONE:  /**/ 0xf3,
    CIPHER_PACKET:  /**/ 0xf4,
    XCLIENT_HELLO:  /**/ 0xf5,
    XSERVER_HELLO:  /**/ 0xf6,
    XEXCHANGE_DONE: /**/ 0xf7,
    XCIPHER_PACKET: /**/ 0xf8,
    ZIPPED_PACKET:  /**/ 0xf9,
    BAG_CLOSE:      /**/ 0x0f,
    BAG_PACKET:     /**/ 0x0e,
};
const MQTT_PACK_CODE = {
    0x10: "connect",
    0x20: "conack",
    0x30: "publish",
    0x40: "pub.ack",
    0x50: "pub.receive",
    0x60: "pub.release",
    0x70: "pub.complete",
    0x80: "subscribe",
    0x90: "suback",
    0xa0: "unsubscribe",
    0xb0: "unsuback",
    0xc0: "ping.request",
    0xd0: "ping.response",
    0xe0: "disconnect",
    0xf0: "auth"
};
const MQTT_PACK_KEYS = Object.fromEntries(
    Object.entries(MQTT_PACK_CODE).map(([id, name]) => [name, parseInt(id)])
);
/** **MQTT V5**.
 * 
 * Relationship code - key      */
const MQTT_V5_CODE = {
    1: "payload_format_indicator",
    2: "message_expiry_interval",
    3: "content_type",
    8: "response_topic",
    9: "correlation_data",
    11: "subscription_identifier",
    17: "session_expiry_interval",
    18: "assigned_client_identifier",
    19: "server_keep_alive",
    21: "authentication_method",
    22: "authentication_data",
    23: "request_problem_information",
    24: "will_delay_interval",
    25: "request_response_information",
    26: "response_information",
    28: "server_reference",
    31: "reason_string",
    34: "receive_maximum",
    35: "topic_alias_maximum",
    36: "topic_alias",
    37: "maximum_qos",
    38: "retain_available",
    39: "user_property",
    40: "maximum_packet_size",
    41: "wildcard_subscription_available",
    42: "subscription_identifiers_available",
    43: "shared_subscription_available"
};
/** **MQTT V5**.
 * 
 * Relationship key - code      */
const MQTT_V5_KEYS = Object.fromEntries(
    Object.entries(MQTT_V5_CODE).map(([id, name]) => [name, parseInt(id)])
);

const ERROR_TABLE = {
    secureError:        /**/ "Acceso no permitido",
    unspecifiedError:   /**/ "Error no especificado",
    loginError:         /**/ "Usuario/Contraseña no corresponden",
    restrictedAccess:   /**/ "Acceso restringido",
    badParameters:      /**/ "Error en los parámetros suministrados",
    atItemError:        /**/ "en item",
    storeNotFound:      /**/ "Tienda no encontrada",
    storeMemberError:   /**/ "Tienda no registrada como miembro",
    storeWalletError:   /**/ "Tienda no posee cuenta en billetera.",
    clientNotFound:     /**/ "Cliente no especificado",
    clientWalletError:  /**/ "Cliente no posee billetera",
    laneNotFound:       /**/ "Carril no especificado",
    saleTypeError:      /**/ "Tipo de venta invalido",
    productNotFound:    /**/ "Producto no encontrado",
    productQtyError:    /**/ "Cantidad de productos no especificada",
    productNotMatch:    /**/ "Producto no corresponde al carril",
    unitPriceError:     /**/ "Precio por unidad negativo",
    taxesNotFound:      /**/ "Tipo de impuesto no encontrado",
    amountError:        /**/ "Error en valor especificado",
    itemsError:         /**/ "No ha especificado items para la venta",
    machineNotFound:    /**/ "Máquina no fue encontrada",
    machineBusy:        /**/ "Máquina se encuentra ocupada",
    machineError:       /**/ "Máquina no conecta",
    uuidNotFound:       /**/ "UUID no especificado",
    uuidAlreadyExists:  /**/ "UUID ya fue utilizado",
    invoiceError:       /**/ "Error al crear Factura",
    paymentError:       /**/ "Error al crear Pago Recibido",
    insufficientFunds:  /**/ "Fondos Insuficientes",
    qrNotSpecified:     /**/ "QR no especificado",
    registerError:      /**/ "Registro no procesado",
};
//
export {
    IOREASON,
    PACK_TYPE,
    MQTT_PACK_CODE,
    MQTT_PACK_KEYS,
    MQTT_V5_CODE,
    MQTT_V5_KEYS,
    ERROR_TABLE,
};


